/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'NRSDKOverview',
    
    {
      type: 'category',
      label: 'XREAL Devices',
      link: {
        type: 'generated-index',
        title: 'XREAL Devices',
        // description: 'Learn about the most important Docusaurus concepts!',
        // slug: '/category/docusaurus-guides',
        // keywords: ['guides'],
        // image: '/img/docusaurus.png',
      },
      items: ['XREALDevices/Compatibility','XREALDevices/Controller','XREALDevices/XREAL Glasses'],
    },

    'Getting Started with NRSDK',

    'Sample Code',
    'Tutorials',
    {
      type: 'category',
      label: 'Release Note',
      link: {
        type: 'generated-index',
        title: 'Release Notes',
        // description: 'Learn about the most important Docusaurus concepts!',
        // slug: '/category/docusaurus-guides',
        // keywords: ['guides'],
        // image: '/img/docusaurus.png',
      },
      items: [
        'Release Note/NRSDK 2.2.0',
        'Release Note/NRSDK 2.1.1',
        'Release Note/NRSDK 2.1.0',
        'Release Note/NRSDK 1.10.2',
        'Release Note/NRSDK 1.9.5',
        'Release Note/NRSDK 1.9.3',
        'Release Note/NRSDK 1.9.1',
        'Release Note/NRSDK 1.8.0',
        'Release Note/NRSDK 1.7.0',
        'Release Note/NRSDK 1.6.0',   
      ],
    },
    {
      type: 'category',
      label: 'Input and Camera',
      link: {
        type: 'generated-index',
        title: 'Input and Camera',
        // description: '11',
        // image: '/img/docusaurus.png',
      },
      items: [
        'Input and Camera/NRInput',
        'Input and Camera/Interact with Unity UI',
        'Input and Camera/Customize Controller UI',
        'Input and Camera/NRCameraRig', 
      ],
    },
    'Hand Tracking',
    {
      type: 'category',
      label: 'Image Tracking',
      link:{type:'doc',id:'Image Tracking/intro'},
      items: [
        'Image Tracking/Marker',
      ],
    },
    {
      type: 'category',
      label: 'Plane Detection (Tutorial)',
      link:{type:'doc',id:'Plane Detection/Overview'},
      items: [
        'Plane Detection/Import the package',
        'Plane Detection/Detect planes in the real world',
        'Plane Detection/Perform a hit test against detected planes',
        'Plane Detection/Add a car',
        'Plane Detection/Add gems',
        'Plane Detection/Wrap up',
      ],
    },
    {
      type: 'category',
      label: 'Depth Mesh',
      link:{type:'doc',id:'Depth Mesh/Overview'},
      items: [
        'Depth Mesh/Meshing Manager Overview',
        'Depth Mesh/Use Meshes in the Editor',
        'Depth Mesh/Tutorial-Mesh Collision',
      ],
    },


    {
      type: 'category',
      label: 'Spatial Anchor',
      link: {type:'doc',id:'Spatial Anchor/intro'}, 
      items: [
        'Spatial Anchor/MappingExampleScene',
        {
          type: 'category',
          label: 'Tutorial-HalloweenTreasureHunt',
          link: {type:'doc',id:'Spatial Anchor/Tutorial-HalloweenTreasureHunt/Intro'},
          items: [
            'Spatial Anchor/Tutorial-HalloweenTreasureHunt/HandletheSituationofFailedAnchorSaving',
          ],
        },
        {
          type: 'category',
          label: 'Tutorial: Sharing Anchors',
          link: {type:'doc',id:'Spatial Anchor/Tutorial-Sharing Anchors/intro'},
          items: [
            'Spatial Anchor/Tutorial-Sharing Anchors/SettingUpPhoton',
            'Spatial Anchor/Tutorial-Sharing Anchors/Firebase',
            'Spatial Anchor/Tutorial-Sharing Anchors/Aliyun',
            'Spatial Anchor/Tutorial-Sharing Anchors/CloudSaveandLoad',
            'Spatial Anchor/Tutorial-Sharing Anchors/SharingAnchorswithPhoton',
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Tools',
      link: {
        type: 'generated-index',
        title: 'Tools',
        // description: 'Learn about the most important Docusaurus concepts!',
        // slug: '/category/docusaurus-guides',
        // keywords: ['guides'],
        // image: '/img/docusaurus.png',
      },
      items: [
        'Tools/Single Pass Stereo Rendering',
        'Tools/First Person View',
        'Tools/Emulator',
        'Tools/XR Streaming',
        'Tools/Dual Screen Display',
      ],
    },

    {
      type: 'category',
      label: 'Miscellaneous',
      link: {
        type: 'generated-index',
        title: 'Miscellaneous',
        // description: 'Learn about the most important Docusaurus concepts!',
        // slug: '/category/docusaurus-guides',
        // keywords: ['guides'],
        // image: '/img/docusaurus.png',
      },
      items: [
        'Miscellaneous/Access RGB Camera',
        'Miscellaneous/NRSDK Coordinate Systems',
        'Miscellaneous/MRTK2 Integration',
        'Miscellaneous/MRTK3 Integration',
        'Miscellaneous/Notification popup',
        'Miscellaneous/Reset Camera',
        'Miscellaneous/Render Metrics',
        'Miscellaneous/Render MonoMode',
      ],
    },
    
    'Frequently Asked Questions',

    {
      type: 'category',
      label: 'Design Guide',
      link: {type:'doc',id:'Design Guide/intro'},
      items: [
        'Design Guide/Display',
        'Design Guide/Interacting',
        'Design Guide/Controlling',
        'Design Guide/Navigating',
      ],
    },
  ],
   
};

export default sidebars;





