/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually


  "tutorialSidebar": [
    "XREALSDKOverview",
    {
      "type": "category",
      "label": "XREAL Devices",
      "link": {
        "type": "generated-index",
        "title": "XREAL Devices"
      },
      "items": [
        "XREALDevices/Compatibility",
        "XREALDevices/XREAL Glasses"
      ]
    },
    "Getting Started with XREAL SDK",
    {
      "type": "category",
      "label": "Migrating from NRSDK to XREAL SDK",
      "link": {
        "type": "doc",
        "id": "MigratingFromNRSDKToXREALSDK/intro"
      },
      "items": [
        "MigratingFromNRSDKToXREALSDK/Migration_PlaneDetection",
        "MigratingFromNRSDKToXREALSDK/Migration_ImageTracking",
        "MigratingFromNRSDKToXREALSDK/Migration_Anchors",
        "MigratingFromNRSDKToXREALSDK/Migration_Meshing"
      ]
    },
    "Sample Code",
    {
      "type": "category",
      "label": "Release Note",
      "link": {
        "type": "generated-index",
        "title": "Release Notes"
      },
      "items": [
        "Release Note/SDK Upgrade Playbook",
        "Release Note/XREAL SDK 3.1.0",
        "Release Note/XREAL SDK 3.0.0"
      ]
    },
    {
      "type": "category",
      "label": "Camera",
      "link": {
        "type": "doc",
        "id": "Camera/Camera"
      },
      "items": [
        "Camera/Access RGB Camera"
      ]
    },
    {
      "type": "category",
      "label": "Input and Interactions",
      "link": {
        "type": "generated-index",
        "title": "Input and Interactions"
      },
      "items": [
        "Input and Interactions/Controller",
        "Input and Interactions/Hand Tracking",
        "Input and Interactions/Gaze",
        "Input and Interactions/Notification popup"
        
      ]
    },
    {
      "type": "category",
      "label": "Image Tracking",
      "link": {
        "type": "doc",
        "id": "Image Tracking/intro"
      },
      "items": [
        "Image Tracking/Marker"
      ]
    },
    "Plane Detection",
    {
      "type": "category",
      "label": "Depth Mesh",
      "link": {
        "type": "doc",
        "id": "Depth Mesh/NormalMesh"
      },
      "items": [
        "Depth Mesh/MeshClassification",
        "Depth Mesh/Use Meshes in the Editor"
      ]
    },
    {
      "type": "category",
      "label": "Spatial Anchor",
      "link": {
        "type": "doc",
        "id": "Spatial Anchor/intro"
      },
      "items": [
        "Spatial Anchor/Anchors"
        
      ]
    },
    "MRTK3_Integration",
    {
      "type": "category",
      "label": "Tools",
      "link": {
        "type": "generated-index",
        "title": "Tools"
      },
      "items": [
       
        "Tools/First Person View",
        "Tools/Emulator",
        "Tools/XR Streaming",
        "Tools/Dual Screen Display",
        "Tools/ControlGlasses"
      ]
    },
    {
      "type": "category",
      "label": "Rendering",
      "link": {
        "type": "generated-index",
        "title": "Rendering"
      },
      "items": [
        "Rendering/Warping",
        "Rendering/Single Pass Stereo Rendering",
        "Rendering/Render Metrics"
      ]
    },

    "pc-sdk-beta",
    "Frequently Asked Questions",
    {
      "type": "category",
      "label": "Design Guide",
      "link": {
        "type": "generated-index",
        "title": "Design Guide",
        "description": "A quick and simple guide aimed at providing fundamental design knowledge as well as establishing some common standards for user interaction in XREAL mixed-reality apps. The guide is broken down into four principle sections:"
      },
      "items": [
        "Design Guide/Display",
        "Design Guide/Interacting",
        "Design Guide/Controlling",
        "Design Guide/Navigating"
      ]
    }
  ]
};



export default sidebars;
