/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    
    {
      type: 'category',
      label: 'XREAL Devices',
      items: ['XREAL Devices/Compatibility','XREAL Devices/Controller','XREAL Devices/XREAL Glasses'],
    },

    'Getting Started with NRSDK',

    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },

    'Sample Code',
    // 'Tutorials',
    {
      type: 'category',
      label: 'Release Note',
      items: [
        'Release Note/NRSDK 2.2.0',
        'Release Note/NRSDK 2.1.1',
        'Release Note/NRSDK 2.1.0',
        'Release Note/NRSDK 1.10.2',
        'Release Note/NRSDK 1.9.5',
        'Release Note/NRSDK 1.9.3',
        'Release Note/NRSDK 1.9.1',
        'Release Note/NRSDK 1.8.0',
        'Release Note/NRSDK 1.7.0',
        'Release Note/NRSDK 1.6.0',   
      ],
    },
  ],
   
};

export default sidebars;
